version: '3.9'
services:
  spring-petclinic:
    image: kimaudwns/bookshop:latest
    container_name: bookshop
    ports:
      - "80:8080"
  oracle-db:
    image: kimaudwns/db:v1
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"
